(cl:in-package synchronizer_laser_imu-msg)
(cl:export '(CLEAN-VAL
          CLEAN
          PUMP-VAL
          PUMP
          LEFT-VAL
          LEFT
          RIGHT-VAL
          RIGHT
          MOP-VAL
          MOP
          PARK-VAL
          PARK
          FORWARD-VAL
          FORWARD
          BACKWARD-VAL
          BACKWARD
          WASH-VAL
          WASH
          SPEED_ENABLE-VAL
          SPEED_ENABLE
          DRIVERLESS-VAL
          DRIVERLESS
          DRIVERLESS_ENABLED-VAL
          DRIVERLESS_ENABLED
          VELOCITY-VAL
          VELOCITY
          ANGLE-VAL
          ANGLE
          ANGLE_VELOCITY-VAL
          ANGLE_VELOCITY
          CHARGE-VAL
          CHARGE
))